"""Shared pytest fixtures for the editor API test suite.

Points the app at throwaway temp dirs + a temp SQLite DB, mocks the Anthropic
client, and provides a tiny fixture library (real 1s clips generated by ffmpeg,
never committed) plus a catalog-only "ghost" row. Tests drive the Flask test
client via create_app(); the real app never needs to be running.
"""
import os
import shutil
import subprocess
import sys
import tempfile
import uuid
from pathlib import Path

import pytest

# --- Point the app at throwaway locations BEFORE importing it. Blueprints do
#     `from core import *`, which copies MEDIA_DIR/paths at import time, so the env
#     and module globals must be set first. ---
_TMP = Path(tempfile.mkdtemp(prefix="cc-tests-"))
_MEDIA = _TMP / "media"
_MEDIA.mkdir(parents=True, exist_ok=True)
_CACHE = _TMP / "cache"
_CACHE.mkdir(parents=True, exist_ok=True)

os.environ["MEDIA_DIR"] = str(_MEDIA)
os.environ.setdefault("ANTHROPIC_API_KEY", "test-key")  # AI is always mocked; never real

sys.path.insert(0, str(Path(__file__).resolve().parent))  # flat-import editor modules

import db  # noqa: E402
db.DB_PATH = _TMP / "editor.db"

import config  # noqa: E402
config.CLIPS_OUT = _TMP / "clips_out"    # export output lands here, not the repo (export.py reads config.CLIPS_OUT)

import core  # noqa: E402

from app import create_app  # noqa: E402
from claude_client import ClipSelection, RoughCutPlan, EditChatResult  # noqa: E402


def _pytest_sessionfinish_cleanup():
    shutil.rmtree(_TMP, ignore_errors=True)


def pytest_sessionfinish(session, exitstatus):
    _pytest_sessionfinish_cleanup()


# --- tiny real media, generated once and copied per-test (fast + isolated) ---
def _make_sample(ext: str) -> Path:
    """Generate a 1s 320x240 H.264 clip in the session cache (once per extension)."""
    dest = _CACHE / f"sample{ext}"
    if dest.exists():
        return dest
    subprocess.run(
        ["ffmpeg", "-y", "-f", "lavfi",
         "-i", "testsrc=duration=1:size=320x240:rate=15",
         "-c:v", "libx264", "-pix_fmt", "yuv420p", "-t", "1", str(dest)],
        check=True, capture_output=True,
    )
    return dest


@pytest.fixture()
def app():
    """Fresh temp DB + clean media dir for each test."""
    db.DB_PATH.unlink(missing_ok=True)
    db.init_db()   # applies the migration chain (all tables, incl. clip_regions)
    for p in _MEDIA.iterdir():
        p.unlink() if p.is_file() else shutil.rmtree(p, ignore_errors=True)
    core._jobs.clear()  # drop any in-memory job state from a prior test
    application = create_app()
    application.config.update(TESTING=True)
    return application


@pytest.fixture()
def client(app):
    return app.test_client()


@pytest.fixture()
def conn():
    c = db.get_conn()
    yield c
    c.close()


@pytest.fixture()
def make_clip(conn):
    """Insert a clip row. present=True drops a real playable file in MEDIA_DIR and sets
    media_path; present=False leaves a catalog-only 'ghost' (no file on disk)."""
    def _make(file_stem, present=True, ext=".mp4", **cols):
        media_path = None
        if present:
            src = _make_sample(ext)
            dest = _MEDIA / f"{file_stem}{ext}"
            shutil.copy(src, dest)
            media_path = str(dest)
        fields = {
            "file_stem": file_stem,
            "duration_s": cols.pop("duration_s", 1.0),
            "kind": cols.pop("kind", "video"),
            "content_hash": cols.pop("content_hash", uuid.uuid4().hex),
            "media_path": media_path,
            "media_status": "present" if present else "absent",
            "description": cols.pop("description", ""),
            "category": cols.pop("category", ""),
            "tags": cols.pop("tags", ""),
            "context": cols.pop("context", ""),
        }
        fields.update(cols)
        keys = ", ".join(fields)
        qs = ", ".join("?" for _ in fields)
        cur = conn.execute(f"INSERT INTO clips ({keys}) VALUES ({qs})", tuple(fields.values()))
        conn.commit()
        return cur.lastrowid
    return _make


@pytest.fixture()
def mock_ai(monkeypatch):
    """Patch the two generation seams (imported into blueprints.edits via `import *`).
    The fakes build selections from the pool they're handed, so returned clip_ids are
    always valid + we can capture which clips the pool exposed. Returns the call log."""
    import blueprints.edits as edits

    calls = {"generate": [], "revise": []}

    def fake_generate(prompt, clips):
        calls["generate"].append({"prompt": prompt, "clips": clips})
        sels = [ClipSelection(clip_id=c["id"], in_point=0.0, out_point=1.0, reason="test")
                for c in clips[:2]]
        return RoughCutPlan(concept="Test concept", selections=sels, aspect=None)

    def fake_revise(instruction, current_timeline, clips):
        calls["revise"].append({"instruction": instruction, "current": current_timeline, "clips": clips})
        # Return the whole pool so the revised timeline visibly differs from a
        # single-item starting timeline (lets the undo test assert a real change).
        sels = [ClipSelection(clip_id=c["id"], in_point=0.0, out_point=1.0, reason="test")
                for c in (clips or [])]
        return EditChatResult(reply="Applied your change.", selections=sels, aspect=None)

    monkeypatch.setattr(edits, "generate_rough_cut", fake_generate)
    monkeypatch.setattr(edits, "revise_edit", fake_revise)
    return calls
